# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QAUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(958, 726)
        font = QtGui.QFont()
        font.setFamily("Caladea")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("decoders.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setSizeGripEnabled(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalFrame_2 = QtWidgets.QFrame(self.frame)
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.horizontalFrame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.question_label = QtWidgets.QLabel(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.question_label.sizePolicy().hasHeightForWidth())
        self.question_label.setSizePolicy(sizePolicy)
        self.question_label.setMaximumSize(QtCore.QSize(16777215, 18))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(17)
        self.question_label.setFont(font)
        self.question_label.setObjectName("question_label")
        self.verticalLayout_4.addWidget(self.question_label, 0, QtCore.Qt.AlignHCenter)
        self.question_textedit = QtWidgets.QTextEdit(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.question_textedit.sizePolicy().hasHeightForWidth())
        self.question_textedit.setSizePolicy(sizePolicy)
        self.question_textedit.setMinimumSize(QtCore.QSize(800, 0))
        self.question_textedit.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(18)
        self.question_textedit.setFont(font)
        self.question_textedit.setTabChangesFocus(True)
        self.question_textedit.setAcceptRichText(False)
        self.question_textedit.setObjectName("question_textedit")
        self.verticalLayout_4.addWidget(self.question_textedit, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.horizontalFrame_2, 0, QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(918, 340))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, -1, -1, 6)
        self.verticalLayout_6.setSpacing(27)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.aradioButton = QtWidgets.QRadioButton(self.frame_2)
        self.aradioButton.setText("")
        self.aradioButton.setChecked(True)
        self.aradioButton.setObjectName("aradioButton")
        self.horizontalLayout_5.addWidget(self.aradioButton)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.alineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.alineEdit.setMinimumSize(QtCore.QSize(510, 32))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(15)
        self.alineEdit.setFont(font)
        self.alineEdit.setObjectName("alineEdit")
        self.horizontalLayout_5.addWidget(self.alineEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bradioButton = QtWidgets.QRadioButton(self.frame_2)
        self.bradioButton.setText("")
        self.bradioButton.setObjectName("bradioButton")
        self.horizontalLayout_6.addWidget(self.bradioButton, 0, QtCore.Qt.AlignLeft)
        self.bLabel_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bLabel_2.setFont(font)
        self.bLabel_2.setObjectName("bLabel_2")
        self.horizontalLayout_6.addWidget(self.bLabel_2, 0, QtCore.Qt.AlignLeft)
        self.bLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.bLineEdit.setMinimumSize(QtCore.QSize(510, 32))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(15)
        self.bLineEdit.setFont(font)
        self.bLineEdit.setObjectName("bLineEdit")
        self.horizontalLayout_6.addWidget(self.bLineEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cradioButton = QtWidgets.QRadioButton(self.frame_2)
        self.cradioButton.setText("")
        self.cradioButton.setObjectName("cradioButton")
        self.horizontalLayout_7.addWidget(self.cradioButton)
        self.cLabel = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cLabel.setFont(font)
        self.cLabel.setObjectName("cLabel")
        self.horizontalLayout_7.addWidget(self.cLabel)
        self.cLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.cLineEdit.setMinimumSize(QtCore.QSize(510, 32))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(15)
        self.cLineEdit.setFont(font)
        self.cLineEdit.setObjectName("cLineEdit")
        self.horizontalLayout_7.addWidget(self.cLineEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.dradioButton = QtWidgets.QRadioButton(self.frame_2)
        self.dradioButton.setText("")
        self.dradioButton.setObjectName("dradioButton")
        self.horizontalLayout_8.addWidget(self.dradioButton)
        self.dLabel = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dLabel.setFont(font)
        self.dLabel.setObjectName("dLabel")
        self.horizontalLayout_8.addWidget(self.dLabel)
        self.dLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.dLineEdit.setMinimumSize(QtCore.QSize(510, 32))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(15)
        self.dLineEdit.setFont(font)
        self.dLineEdit.setObjectName("dLineEdit")
        self.horizontalLayout_8.addWidget(self.dLineEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(822, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.codesnippet_textedit = QtWidgets.QTextEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.codesnippet_textedit.sizePolicy().hasHeightForWidth())
        self.codesnippet_textedit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(15)
        self.codesnippet_textedit.setFont(font)
        self.codesnippet_textedit.setObjectName("codesnippet_textedit")
        self.verticalLayout_5.addWidget(self.codesnippet_textedit)
        self.verticalLayout.addWidget(self.frame_3, 0, QtCore.Qt.AlignHCenter)
        self.submit_PushButton = QtWidgets.QPushButton(self.frame)
        self.submit_PushButton.setMinimumSize(QtCore.QSize(160, 0))
        self.submit_PushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Longdon Decorative")
        font.setPointSize(17)
        self.submit_PushButton.setFont(font)
        self.submit_PushButton.setObjectName("submit_PushButton")
        self.verticalLayout.addWidget(self.submit_PushButton, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.label_2.setBuddy(self.alineEdit)
        self.bLabel_2.setBuddy(self.bLineEdit)
        self.cLabel.setBuddy(self.cLineEdit)
        self.dLabel.setBuddy(self.dLineEdit)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.question_textedit, self.alineEdit)
        Dialog.setTabOrder(self.alineEdit, self.bLineEdit)
        Dialog.setTabOrder(self.bLineEdit, self.cLineEdit)
        Dialog.setTabOrder(self.cLineEdit, self.dLineEdit)
        Dialog.setTabOrder(self.dLineEdit, self.codesnippet_textedit)
        Dialog.setTabOrder(self.codesnippet_textedit, self.submit_PushButton)
        Dialog.setTabOrder(self.submit_PushButton, self.aradioButton)
        Dialog.setTabOrder(self.aradioButton, self.bradioButton)
        Dialog.setTabOrder(self.bradioButton, self.cradioButton)
        Dialog.setTabOrder(self.cradioButton, self.dradioButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Decoders"))
        self.question_label.setText(_translate("Dialog", "Question"))
        self.label_2.setText(_translate("Dialog", "A )"))
        self.bLabel_2.setText(_translate("Dialog", "B )"))
        self.cLabel.setText(_translate("Dialog", "C )"))
        self.dLabel.setText(_translate("Dialog", "D )"))
        self.codesnippet_textedit.setStatusTip(_translate("Dialog", "Code Snippet"))
        self.submit_PushButton.setText(_translate("Dialog", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

